local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("NOLIFE HUB", "DarkTheme")
local Tab = Window:NewTab("Main")
local Section = Tab:NewSection("Melee")
Section:NewButton("BuyDeathStep", "ButtonInfo", function()
    game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("BuyDeathStep")
end)
Section:NewButton("BuyElectricClaw", "ButtonInfo", function()
    game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("BuyElectricClaw")
end)
Section:NewButton("BuySuperhuman", "ButtonInfo", function()
    game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("BuySuperhuman")
end)
Section:NewButton("BuyGodhuman", "ButtonInfo", function()
    game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("BuyGodhuman")
end)
Section:NewButton("BuySharkmanKarate", "ButtonInfo", function()
    game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("BuySharkmanKarate")
end)
Section:NewButton("Restats", "ButtonInfo", function()
    local args = {
    [1] = "BlackbeardReward",
    [2] = "Refund",
    [3] = "2"
}

game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer(unpack(args))
end)
local Tab = Window:NewTab("TP World")
local Section = Tab:NewSection("TP World")
Section:NewButton("TP World1", "ButtonInfo", function()
    game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("TravelMain")
end)
Section:NewButton("TP World2", "ButtonInfo", function()
    game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("TravelDressrosa")
end)
Section:NewButton("TP World3", "ButtonInfo", function()
    game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer("TravelZou")
end)
local Tab = Window:NewTab("setting")
local Section = Tab:NewSection("Hide Ui")
Section:NewKeybind("KeybindText", "KeybindInfo", Enum.KeyCode.RightControl, function()
	Library:ToggleUI()
end)
